server:
  port: 80

zuul:
  routes:
    movies:
      url: http://localhost:5001
    customer:
      url: http://localhost:5002

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - health
