server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost/dvdrental
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - health
